name: Build and publish

on: [push, pull_request]

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['10.1.1', '10.1.2']

    steps:
      - name: Checkout GhidraOrbis
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: Checkout Ghidra-Cpp-Class-Analyzer
        uses: actions/checkout@v3
        with:
          repository: astrelsky/Ghidra-Cpp-Class-Analyzer
          path: Ghidra-Cpp-Class-Analyzer

      - name: Build Ghidra-Cpp-Class-Analyzer
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 6.9
          build-root-directory: Ghidra-Cpp-Class-Analyzer
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Install the class analyzer as an extension forcefully
        run: |
           mkdir -p ~/.ghidra/.ghidra_${{ matrix.ghidra }}_PUBLIC/Extensions/
           unzip Ghidra-Cpp-Class-Analyzer/dist/*.zip -d ~/.ghidra/.ghidra_${{ matrix.ghidra }}_PUBLIC/Extensions/

      - name: Make artifact single zip 
        run: |
          mkdir Ghidra-Cpp-Class-Analyzer_bin
          unzip Ghidra-Cpp-Class-Analyzer/dist/*.zip -d Ghidra-Cpp-Class-Analyzer_bin

      - name: Upload Ghidra-Cpp-Class-Analyzer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ghidra-Cpp-Class-Analyzer_${{ matrix.ghidra }}_${{ env.SHORT_SHA }}
          path: Ghidra-Cpp-Class-Analyzer_bin/*

      - name: Cleanup
        run: rm -rf Ghidra-Cpp-Class-Analyzer

      - name: Build GhidraOrbis
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 6.9
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Make artifact single zip 
        run: |
          mkdir GhidraOrbis_dist
          unzip dist/*.zip -d GhidraOrbis_dist/

      - name: Upload GhidraOrbis Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GhidraOrbis_${{ matrix.ghidra }}_${{ env.SHORT_SHA }}
          path: GhidraOrbis_dist/*

  push_release:
    #if: |
      #github.event.action != 'pull_request' &&
      #github.repository == 'astrelsky/GhidraOrbis'
    needs: build_extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Re-zip artifacts
        id: zip
        run: |
          for artifact in artifacts/*; do
            7z a ${artifact}.zip "./${artifact}/*"
          done
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls artifacts 
          gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifacts/*.zip --target ${{ GITHUB.SHA }} ${{ GITHUB.RUN_NUMBER }} -t 1.0${{ GITHUB.RUN_NUMBER }}

