name: Build and publish

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['10.3', '10.3.1', '10.3.2', '10.3.3', '10.4' ]

    steps:
      - name: Checkout GhidraOrbis
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt 

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Ghidra
        uses: illusion0001/setup-ghidra@patch-2
        with:
          version: ${{ matrix.ghidra }}

      - name: Build GhidraOrbis
        run: gradle buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Upload GhidraOrbis Artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.zip
          if-no-files-found: error

  push_release:
    if: |
      github.event_name == 'push' &&
      github.repository == 'astrelsky/GhidraOrbis'
    needs: build_extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}
